# Generated by Django 4.1.6 on 2023-02-05 01:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mail', models.EmailField(max_length=100, null=True)),
                ('telefon', models.CharField(max_length=12, null=True, verbose_name='telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Image_for_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('name', models.CharField(max_length=300, null=True)),
                ('adres', models.CharField(max_length=300, null=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('date', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(default='website', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_resmi', models.ImageField(null=True, upload_to='image/')),
                ('body', ckeditor.fields.RichTextField(default='portfolio', null=True)),
                ('body_tr', ckeditor.fields.RichTextField(default='portfolio', null=True)),
                ('body_en', ckeditor.fields.RichTextField(default='portfolio', null=True)),
                ('cv_resmi', models.ImageField(null=True, upload_to='image/')),
                ('cv', models.FileField(upload_to='files/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('read', models.IntegerField(default=0)),
                ('completed', models.CharField(choices=[('completed', 'completed'), ('draft', 'draft')], default='completed', max_length=200)),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('body_tr', ckeditor.fields.RichTextField(null=True)),
                ('body_en', ckeditor.fields.RichTextField(null=True)),
                ('read_time', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='can.category')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='can.comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='can.post')),
            ],
        ),
    ]
