# Generated by Django 4.0.3 on 2023-02-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('can', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
